apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: gamification-queue # name of this custom resource; does not have to the same as the actual queue name
spec:
  name: gamification.queue # name of the queue
  durable: true
  rabbitmqClusterReference:
    name: keglingpet-rabbitmq
