apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: keglingpet-permission
spec:
  vhost: "/" # name of a vhost
  user: "keglingpet" # name of a RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: keglingpet-rabbitmq  # rabbitmqCluster must exist in the same namespace as this resource
