apiVersion: v1
kind: Secret
metadata:
  name: credentials-secret
type: Opaque
stringData:
  username: keglingpet
  password: keglingpet
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: keglingpet
spec:
  tags:
  - administrator # available tags are 'management', 'policymaker', 'monitoring' and 'administrator'
  rabbitmqClusterReference:
    name: keglingpet-rabbitmq # rabbitmqCluster must exist in the same namespace as this resource
  importCredentialsSecret:
    name: credentials-secret
